### ISSUE TITLE
How to use the new callbackMapSet feature

### ISSUE THREAD

**Issue by cosmointeractive** [bjorn2404/jQuery-Store-Locator-Plugin#139]
Hello, I looked at your blog and can't seem to find any examples on using the callback features. Is there some place else to find them?

**Comment by bjorn2404** [comment]
I don't have them documented at the moment. The callback functions work like they would work for any jQuery plugin. They allow you to add custom functionality during a certain point when the plugin is running and are often tied to events. I added callbackMapSet specifically because I used the plugin on a project where the map was initially hidden and you can tab between the results and map. With Google Maps if the map is initially out of view it needs to be re-centered, resized and the zoom had to be set again for it to function like you'd expect. Anyways, this specific callback will run after the map is loaded and has four parameters available:

- map: Google Maps object
- originPoint: Google LatLng object of the origin coordinates
- originalZoom: The initial map zoom level
- myOptions: All of the map settings

An example would look like this:

```javascript
$('#bh-sl-map-container').storeLocator({
    callbackMapSet: function( map, originPoint, originalZoom, myOptions ) {
        // Your custom functionality goes here
    }
});
```

**Comment by cosmointeractive** [comment]
Thank you for taking the time to reply. I look forward to the documentation when finished. In the mean time, where can one satisfied gent buy a gent like you some coffee for this amazing plugin?

**Comment by bjorn2404** [comment]
Thanks, I'd rather you just donate to your favorite charity. There's another callback documentation issue open so I'm going to close this one.
