### ISSUE TITLE
Custom category markers with list icons

### ISSUE THREAD

**Issue by subindesign** [bjorn2404/jQuery-Store-Locator-Plugin#142]
This is a fantastic plugin, Thank you sincerely for all of your work.

https://bjornblog.com/storelocator/v2/category-markers-example.html

Based on your Custom category markers example above.

Can I change list icons matching the custom category markers instead A,B,C?

```
<div class="list-label">{{marker}}</div>

<div class="list-label">{{catMarkers}}</div> <-- does not work
```

![skitch 2016-08-04 15-26-00](https://cloud.githubusercontent.com/assets/5760573/17391280/2d3237d8-5a58-11e6-8c7c-057e6693baa2.jpg)

**Comment by bjorn2404** [comment]
catMarkers is not output to the templates and it wouldn't work if it was because the markers are set up using the Google Maps API with the provided images. If you have multiple categories per location I'm not sure what the best route would be. If you're using one category per location you could use {{category}} in the list label class attribute or make a new data-category="{{category}}" attribute. Then set a background image from it in CSS. However, you'd probably also want to create a custom [Handlebars helper](http://handlebarsjs.com/block_helpers.html) to make the category name a "slug" - avoiding uppercase letters and spaces. An example of a Handlebars helper can also be seen in the 169 of the plugin with the niceURL helper.
