### ISSUE TITLE
"API without a callback is not supported"

### ISSUE THREAD

**Issue by shpemu** [bjorn2404/jQuery-Store-Locator-Plugin#289]
Hi all. What general callback should I use in the API link for this feature? I keep getting the error message, "API without a callback is not supported." Thoughts?

**Comment by bjorn2404** [comment]
Google recently (late January) started enforcing this, which is why the console error is appearing. It does not affect functionality but a temporary workaround is to add `callback=Function.prototype` to the Google Maps API as a query string parameter include such as: `https://maps.google.com/maps/api/js?callback=Function.prototype`. This just tells the callback to do nothing. I haven't decided yet if I'll make any changes beyond that to actually use the callback.

**Comment by shpemu** [comment]
I'll give that a try. Thank you!

**Comment by sm-mdp** [comment]
I meant to reply back. That worked. Thank you!
