### ISSUE TITLE
queryStringParams documentation

### ISSUE THREAD

**Issue by jotapee** [bjorn2404/jQuery-Store-Locator-Plugin#59]
Hi, 
I'd be really interested in see some documentation for the queryStringParams feature for the plugin.

I'm trying to implement a form (prior to results page) that send the variables of search and then redirect to the results page.

I think that's what the queryStringParams option is but couldn't find any kind of documentation/example of how to use it.

Thanks in advance.

**Comment by bjorn2404** [comment]
Added an example blog post: http://www.bjornblog.com/web/using-query-string-parameters-with-the-jquery-store-locator

**Comment by jotapee** [comment]
Thank you!

**Comment by jughead47** [comment]
You need to make sure ‘fullMapStart’ is set to true. I don't think that is stated in the tutorial.

**Comment by jughead47** [comment]
I have the query string working. However, I have another search form on the results/map/locator page. If I use that search after I use a query string from another page, the map and listings do not update, I  believe because the get method keeps the query string in the url. How would I go about getting this search form to work? Is there a way to use the post method to get it working?

**Comment by bjorn2404** [comment]
@jotapee you shouldn't have to do that if you're using the latest version of the plugin.

@jughead47 Looks like it's a bug. I'll reopen this issue - not sure when I'll get to it but I might have time this weekend.

**Comment by jughead47** [comment]
@bjorn2404 Thank you, much appreciated.

**Comment by bjorn2404** [comment]
@jughead47 v2.0.8 has the fix for your issue.

**Comment by jughead47** [comment]
@bjorn2404 Thank you very much! Working perfectly!
